# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "rspec", "~> 3.10"

gem "httparty", "~> 0.18.1"

gem "tty-prompt", "~> 0.22.0"

gem "artii", "~> 2.1"

gem "tty-box", "~> 0.6.0"
